from nodes import SingleListNode
from single_list_node import Lista
lista1=Lista()
# print(lista1.size())
# print(lista1.size())
# print(lista1.is_empty())
# lista1.insert_first(10)
# lista1.size()
# print(lista1.is_empty())
# lista1.insert_first(1)
# lista1.insert_first(5)
# lista1.insert_first(5)
# lista1.insert_first(5)
# # lista1.iterator()
# # lista1.insert_last(99)
# # lista1.iterator()
# # lista1.remove_first()
# lista1.iterator()
# # lista1.remove_last()
# # lista1.iterator()
# # lista1.get_first()
# # lista1.get_last()
# # print(lista1.get(4))
# print(lista1.find(5))
# lista1.insert(7,2)
# lista1.iterator()
# lista1.insert_first(1)
# lista1.insert_first(2)
# lista1.insert_first(3)
# lista1.insert_first(4)
# lista1.insert_first(5)
# lista1.insert_first(6)
# lista1.insert(9,5)
# lista1.iterator()
lista1.insert_first(1)
lista1.insert_first(1)
lista1.insert_first(1)
# lista1.iterator()
lista1.make_empty()
lista1.iterator()